# Generated by Django 5.2.4 on 2025-07-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
