# Generated by Django 5.2.4 on 2025-07-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0006_remove_homework_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworksubmission',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
